def test_calibration_live():
  set_tcp(p[0.0,0.0,0.2505,0.0,0.0,0.0])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(1)
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  set_target_payload(2.260000, [-0.011000, 0.004000, 0.073000], [0.005991, 0.005991, 0.005991, 0.000000, 0.000000, 0.000000])
  step_count_6879f789_91d0_4090_882a_a29b4706db19 = 0.0
  thread Step_Counter_Thread_7dba8c81_5e1d_4557_99ad_9a459189569b():
    while (True):
      step_count_6879f789_91d0_4090_882a_a29b4706db19 = step_count_6879f789_91d0_4090_882a_a29b4706db19 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_7dba8c81_5e1d_4557_99ad_9a459189569b()
  global Bin1=p[0.182829499211491,-0.31599183731772934,0.12098501050339178,2.2036803227058535,-2.2363193378226676,-0.00844733517379955]
  global Bin2=p[-0.017098588478363107,-0.3118063131340838,0.1200303801430907,0.008134537013944126,0.004632074070180949,3.120787872374472]
  global base_plate=p[0.36881237191148547,-0.6000691173989049,-0.0027197573347747805,-0.005825777676998524,-0.0028408219250887585,1.5707632180069593]
  global cam_bin1=p[0.015246587324777763,-0.48632105149032473,0.1991416605260554,2.2238502978308787,-2.2151871723437186,-0.002876938519447563]
  global cam_bin2=p[-0.18471565021029393,-0.48713770995455663,0.1998023730738432,2.223835378588522,-2.2152176892310154,-0.0028636673500633363]
  # begin: URCap Installation Node
  #   Source: DTI UR Library, 0.3.0, Danish Technological Institute
  #   Type: DTI UR Library
  ############################################################################
  # Copyright (C) Danish Technological Institute - All Rights Reserved       #
  # Unauthorized copying of this file, via any medium is strictly prohibited #
  # Proprietary and confidential                                             #
  # Written by Jens-Jakob Bentsen <jebe@dti.dk>, November 2020               #
  #                                                                          #
  # Force based moving and force checking                                    #
  #                                                                          #
  # Version                                                                  #
  dti_force_version = 2                                                      #
  #                                                                          #
  # dependencies on other DTI script files                                   #
  # int_dummy = NO_DEPENDENCIES                                              #
  #                                                                          #
  ############################################################################

  def get_dti_force_version():
    return dti_force_version
  end

  def get_dti_force_deps():
    # NO DEPS
    return True
  end


  # like UR's builtin get_tcp_force(), but return the force and torque values transformed
  # along the axes of the given pose
  # param pose: any valid pose, defaults to base, the x, y, and z values are ignored
  # return: 6D force vector with [Fx, Fy, Fz, Mx, My, Mz] aligned to pose in N and Nm respectively
  def get_tcp_force_in_frame(pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):

    # we are only interested in the rotation of pose, set translations to zero
    local target_pose = pose
    target_pose[0] = 0
    target_pose[1] = 0
    target_pose[2] = 0

    # the conversion needs to happen as poses, so we need to convert back and forth a bit
    local force = get_tcp_force()
    local force_vector_as_pose = p[force[0], force[1], force[2], 0, 0, 0]
    local torque_vector_as_pose = p[force[3], force[4], force[5], 0, 0, 0]
    local transformed_force_as_pose = pose_trans(pose_inv(target_pose), force_vector_as_pose)
    local transformed_torque_as_pose = pose_trans(pose_inv(target_pose),torque_vector_as_pose)
    return [transformed_force_as_pose[0], transformed_force_as_pose[1], transformed_force_as_pose[2], transformed_torque_as_pose[0], transformed_torque_as_pose[1], transformed_torque_as_pose[2]]
  end

  # get the force or torque values at the TCP along a single axis of the given pose
  # param axis: number of axis of pose, 0=x, 1=y, ...
  # param pose:  any valid pose, defaults to base, , the x, y, and z values are ignored
  # return: force or torque value in N or Nm respectively
  def get_tcp_force_1d(axis, pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):
    local force_vector = get_tcp_force_in_frame(pose)
    return force_vector[axis]
  end

  # perform a linear move while constantly checking the force; the move is aborted
  # if the force is exceeded and the robot is stopped
  # note: utilizes the currently active TCP
  # note: while running, check the value of the "current_force_vector" variable to check your forces in the given reference pose
  # param p_target: traget pose in base frame
  # param move_parameters: array [r, a, v] with
  #                        r: blend radius for linear move in m
  #                        a: accleration for linear move in m/s^2
  #                        v: velocity for linear move in m/s
  # param max_forces: maximum allowed absolute force in N along the reference pose's x, y, and z axis as vector [Fx, Fy, Fz]
  # param ignore_dists: array of [start_dist, end_dist] ignore the force value within these distances from the
  #                     start and end point, respectively
  #                     (gets around high force readings from acceleration / deceleration)
  # param refrence_pose: measure the allowed forces along the axes of this pose, defaults to the robot's base,
  #                      x, y, and z values of the pose are ignored
  # return: True if end of linear move was reached, else False
  def movel_checkforce(p_target, move_parameters, max_forces, ignore_dists=[0.0, 0.0], reference_pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):

    global p_thread_move_target = p_target
    global thread_move_params = move_parameters
    global thread_target_reached = False
    local p_current = get_actual_tcp_pose()  # current pose
    local p_start = get_actual_tcp_pose()  # start pose of move

    # we use this thread to do the moving
    thread move_thread():
      movel(p_thread_move_target, a=thread_move_params[0], v=thread_move_params[1], r=thread_move_params[2])
      thread_target_reached = True
      sync()
      sync()
    end

    # spin the moving thread and keep track of the force
    move_thread_handler = run move_thread()
    while(not thread_target_reached):
      p_current = get_actual_tcp_pose()
      global current_force_vector = get_tcp_force_in_frame(reference_pose)
      if point_dist(p_current, p_start) > ignore_dists[0] and point_dist(p_current, p_target) > ignore_dists[1]:
        if (norm(current_force_vector[0]) > max_forces[0]) or (norm(current_force_vector[1]) > max_forces[1]) or (norm(current_force_vector[2]) > max_forces[2]):
          kill move_thread_handler
          stopl(1)  # TODO: make this value accessible?
          return False
        end
      end
      sync()
    end
    return True
  end


  # Note 1 to self: a target pose in a feature can be converted to the robot's base frame by
  # using pose_in_base = pose_trans(feature_name, pose_in_feature)
  ############################################################################
  # Copyright (C) Danish Technological Institute - All Rights Reserved       #
  # Unauthorized copying of this file, via any medium is strictly prohibited #
  # Proprietary and confidential                                             #
  # Written by AUTHOR <AUTH@dti.dk>, MONTH YEAR                              #
  #                                                                          #
  # Calculation of poses by offsetting a given pose                          #
  #                                                                          #
  # Version                                                                  #
  dti_relative_poses_version = 1                                             #
  #                                                                          #
  ############################################################################

  def get_dti_relative_poses_version():
    return dti_relative_poses_version
  end

  def get_dti_relative_poses_deps():
    # NO DEPS
    return True
  end

  # TODO: testing
  # Note: Poses in UR-script are given as [translation, axis-angle-rotation],
  # NOT [translation, rpy]!!!


  # calculate a pose by giving an offset to a "base"-pose
  # param base_pose: pose that will be offset
  # param pose_delta: amount to offset along each axis of base_pose
  def p_rel(base_pose, pose_delta=p[0, 0, 0, 0, 0, 0]):
    return pose_trans(base_pose, pose_delta)
  end


  # calculate a pose by giving an offset to a "base"-pose in one dimension
  # param base_pose: pose that will be offset
  # param delta: offset along axis in meters / radians
  # param axis: number of axis along which to offset, x=0, y=1, ..., must be in [0, 5]
  def p_rel_1D(base_pose, delta, axis):
    local p_delta = p[0, 0, 0, 0, 0, 0]
    p_delta[axis] = delta
    return p_rel(base_pose, p_delta)
  end


  # offset a pose along its x-axis, see documentation of p_rel_1D
  def p_rel_x(base_pose, delta):
    return p_rel_1D(base_pose, delta, 0)
  end


  # offset a pose along its y-axis, see documentation of p_rel_1D
  def p_rel_y(base_pose, delta):
    return p_rel_1D(base_pose, delta, 1)
  end


  # offset a pose along its z-axis, see documentation of p_rel_1D
  def p_rel_z(base_pose, delta):
    return p_rel_1D(base_pose, delta, 2)
  end


  # offset a pose by rotating around its x-axis in rad, see documentation of p_rel_1D
  def p_rel_Rx(base_pose, delta):
    return p_rel_1D(base_pose, delta, 3)
  end


  # offset a pose by rotating around its y-axis in rad, see documentation of p_rel_1D
  def p_rel_Ry(base_pose, delta):
    return p_rel_1D(base_pose, delta, 4)
  end


  # offset a pose by rotating around its z-axis in rad, see documentation of p_rel_1D
  def p_rel_Rz(base_pose, delta):
    return p_rel_1D(base_pose, delta, 5)
  end
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: SCHUNK Gripper EGI for UR, 0.1.1, SCHUNK GmbH & Co.
  #   Type: SCHUNK EGI Gripper
  ##################################
  ### SCHUNK EGI VARS            ###
  ##################################


  # Connection data:
  SCHUNK_EGI_HOST = "127.0.0.1"
  SCHUNK_EGI_PORT = "56789"
  global SCHUNK_egi_daemon = rpc_factory("xmlrpc", "http://"+ SCHUNK_EGI_HOST + ":" + SCHUNK_EGI_PORT )

  egiTargetPos = 0
  egiPosTolerance = 0.5

  ##################################
  ### SCHUNK egi HELPER FUNC     ###
  ##################################


  def egiPopup(text):
  	popup(text + str_cat(" Errorcode(int): ", SCHUNK_egi_daemon.egi_error_code()) , "SCHUNK EGI ERROR", warning=False, error=True, blocking=True)
  end

  def setTargets(TargetPos, PosTol):
  	egiTargetPos = TargetPos
  	egiPosTolerance = PosTol
  end


  def egiIsInPos():
  	return egiTargetPosReached()
  end


  def egiGraspOK():
  	local posOk = norm( (egiActualPosition()/1000.0) - egiTargetPos ) < egiPosTolerance
  	local gripped = SCHUNK_egi_daemon.egi_gripped()

  	if gripped and posOk:
  		return True
  	else:
  		return False
  	end
  end





  ##################################
  ### SCHUNK EGI XML-RPC CONTROL ###
  ##################################

  def egiReferencing(sync = True):
  	local success = SCHUNK_egi_daemon.egi_referencing(sync)

  	if not success:
  		egiPopup("Error in egi_referencing()")
  	end

  	return success
  end


  def egiRestartModule(sync = True):
  	local shutdown_ok = SCHUNK_egi_daemon.egi_prepare_shutdown()
  	sleep(1)
  	local success = False

  	if SCHUNK_egi_daemon.egi_ready_shutdown():
  		success = SCHUNK_egi_daemon.egi_restart_module(sync)
  	else:
  		success = False
  		egiPopup("EGI is not ready for shutdown")
  	end

  	if not success:
  		egiPopup("Error in egi_restart_module()")
  	end

  	return success
  end

  def egiPrepareShutdown():
  	local shutdown_ok = SCHUNK_egi_daemon.egi_prepare_shutdown()
  	sleep(1)
  	local success = True

  	if not SCHUNK_egi_daemon.egi_ready_shutdown():
  		success = False
  		egiPopup("EGI is not ready for shutdown")
  	end

  	return success
  end

  def egiPosMove(position, speed, sync):

  	local success = SCHUNK_egi_daemon.egi_pos_move(position*1000, speed*1000, sync)

  	if not success:
  		egiPopup("Error in egi_pos_move()")
  	end

  	return success
  end


  def egiRelPosMove(position, speed, sync):
  	local success = SCHUNK_egi_daemon.egi_rel_pos_move(position*1000, speed*1000, sync)

  	if not success:
  		egiPopup("Error in egi_rel_pos_move()")
  	end

  	return success
  end

  def egiGripWorkPiece(force, inside, sync):
  	local success = SCHUNK_egi_daemon.egi_grip_work_piece(force*1000, inside, sync)

  	if (not success) and egiFatalError() :
  		egiPopup("Error in egi_grip_work_piece()")
  	end

  	return success
  end

  def egiReleaseWorkPiece(sync):
  	local success = SCHUNK_egi_daemon.egi_release_work_piece(sync)

  	if (not success) and egiFatalError():
  		egiPopup("Error in egi_release_work_piece()")
  	end

  	return success
  end



  def egiStop():
  	local success = SCHUNK_egi_daemon.egi_stop()

  	if not success:
  		egiPopup("Error in egi_stop()")
  	end

  	return success
  end


  def egiFastStop():
  	local success = SCHUNK_egi_daemon.egi_quick_stop()

  	if not success:
  		egiPopup("Error in egi_quick_stop()")
  	end

  	return success
  end


  def egiStatusString():
  	return SCHUNK_egi_daemon.egi_status_string()
  end


  def egiActualPosition():
  	return SCHUNK_egi_daemon.egi_actual_position()
  end

  def egiAckError():
  	local success = SCHUNK_egi_daemon.egi_acknowledge_error()

  	if not success:
  		egiPopup("Error in egi_acknowledge_error()")
  	end

  	return success
  end

  def egiTargetPosReached():
  	return SCHUNK_egi_daemon.egi_target_pos_reached()
  end

  def egiModuleRef():
  	return SCHUNK_egi_daemon.egi_module_ref()
  end

  def egiWarning():
  	return SCHUNK_egi_daemon.egi_warning()
  end


  def egiFatalError():
  	return SCHUNK_egi_daemon.egi_fatal_error()
  end

  def egiGripped():
  	return SCHUNK_egi_daemon.egi_gripped()
  end

  def egiNoPart():
  	return SCHUNK_egi_daemon.egi_no_part_detect()
  end


  def egiConnected():
  	return SCHUNK_egi_daemon.egi_connected()
  end


  def egiErrorCode():
  	return SCHUNK_egi_daemon.egi_error_code()
  end


  ######################################
  ### SCHUNK EGI XML-RPC CONTROL END ###
  ######################################
  # end: URCap Installation Node
  $ 1 "BeforeStart"
  $ 2 "calib_server≔rpc_factory('xmlrpc', 'http://192.168.1.119:10000')"
  global calib_server=rpc_factory("xmlrpc", "http://192.168.1.119:10000")
  $ 3 "Robot Program"
  $ 4 "tcp_pose≔get_actual_tcp_pose()"
  global tcp_pose= get_actual_tcp_pose ()
  $ 5 "board_pose≔calib_server.test_extrinsic_calibration(get_actual_tool_flange_pose())"
  global board_pose=calib_server.test_extrinsic_calibration(get_actual_tool_flange_pose())
  $ 8 "board_pose[3]=tcp_pose[3]"
  board_pose[3]=tcp_pose[3]
  $ 9 "board_pose[4]=tcp_pose[4]"
  board_pose[4]=tcp_pose[4]
  $ 10 "board_pose[5]=tcp_pose[5]"
  board_pose[5]=tcp_pose[5]
  $ 11 "board_pose[2]=board_pose[2]+0.01"
  board_pose[2]=board_pose[2]+0.01
  $ 12 "Popup: Moving to board origin now!"
  popup("Moving to board origin now!", "Warning", True, False, blocking=True)
  $ 13 "MoveL"
  $ 14 "board_pose" "breakAfter"
  movel(board_pose, a=1.2, v=0.25)
end
