def test():
  set_gravity([0.0, 0.0, 9.82])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[-0.0567,0.0325,0.0062,-0.0037,-0.0098,-1.5604])
  set_payload(1.17, [-0.003, 0.002, 0.053])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  step_count_bcf005fc_6584_4d3a_a1f1_2415d84648ae = 0.0
  thread Step_Counter_Thread_0924546b_36a1_4f68_92e1_042f360451e0():
    while (True):
      step_count_bcf005fc_6584_4d3a_a1f1_2415d84648ae = step_count_bcf005fc_6584_4d3a_a1f1_2415d84648ae + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_0924546b_36a1_4f68_92e1_042f360451e0()
  set_safety_mode_transition_hardness(1)
  global above_bin1=p[-0.28482989139219683,-0.6102767166149106,0.14066650553811388,-2.2224820731336505,-2.2166355065979455,-0.0026989556738711133]
  global above_bin2=p[-0.08480305180860655,-0.6108108869885609,0.14050959661376208,-2.2224686356704177,-2.216659532242512,-0.00278634108800073]
  global base_plate=p[-0.024014100380523113,-0.8116654278566232,-0.005754309664523227,-0.004671807839145878,5.094047199987354E-4,1.570760575052942]
  global cam_bin1=p[-0.22453649325532635,-0.6110133233587597,0.19305524180988365,-3.138488979012992,4.538484320374063E-4,9.880545786323813E-4]
  global cam_bin2=p[-0.024536558404243708,-0.6110527851165684,0.19289370271920656,-3.138371619092444,4.5408998295626746E-4,9.584763864674526E-4]
  # begin: URCap Installation Node
  #   Source: DTI UR Library, 0.3.0, Danish Technological Institute
  #   Type: DTI UR Library
  ############################################################################
  # Copyright (C) Danish Technological Institute - All Rights Reserved       #
  # Unauthorized copying of this file, via any medium is strictly prohibited #
  # Proprietary and confidential                                             #
  # Written by Jens-Jakob Bentsen <jebe@dti.dk>, November 2020               #
  #                                                                          #
  # Force based moving and force checking                                    #
  #                                                                          #
  # Version                                                                  #
  dti_force_version = 2                                                      #
  #                                                                          #
  # dependencies on other DTI script files                                   #
  # int_dummy = NO_DEPENDENCIES                                              #
  #                                                                          #
  ############################################################################

  def get_dti_force_version():
    return dti_force_version
  end

  def get_dti_force_deps():
    # NO DEPS
    return True
  end


  # like UR's builtin get_tcp_force(), but return the force and torque values transformed
  # along the axes of the given pose
  # param pose: any valid pose, defaults to base, the x, y, and z values are ignored
  # return: 6D force vector with [Fx, Fy, Fz, Mx, My, Mz] aligned to pose in N and Nm respectively
  def get_tcp_force_in_frame(pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):

    # we are only interested in the rotation of pose, set translations to zero
    local target_pose = pose
    target_pose[0] = 0
    target_pose[1] = 0
    target_pose[2] = 0

    # the conversion needs to happen as poses, so we need to convert back and forth a bit
    local force = get_tcp_force()
    local force_vector_as_pose = p[force[0], force[1], force[2], 0, 0, 0]
    local torque_vector_as_pose = p[force[3], force[4], force[5], 0, 0, 0]
    local transformed_force_as_pose = pose_trans(pose_inv(target_pose), force_vector_as_pose)
    local transformed_torque_as_pose = pose_trans(pose_inv(target_pose),torque_vector_as_pose)
    return [transformed_force_as_pose[0], transformed_force_as_pose[1], transformed_force_as_pose[2], transformed_torque_as_pose[0], transformed_torque_as_pose[1], transformed_torque_as_pose[2]]
  end

  # get the force or torque values at the TCP along a single axis of the given pose
  # param axis: number of axis of pose, 0=x, 1=y, ...
  # param pose:  any valid pose, defaults to base, , the x, y, and z values are ignored
  # return: force or torque value in N or Nm respectively
  def get_tcp_force_1d(axis, pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):
    local force_vector = get_tcp_force_in_frame(pose)
    return force_vector[axis]
  end

  # perform a linear move while constantly checking the force; the move is aborted
  # if the force is exceeded and the robot is stopped
  # note: utilizes the currently active TCP
  # note: while running, check the value of the "current_force_vector" variable to check your forces in the given reference pose
  # param p_target: traget pose in base frame
  # param move_parameters: array [r, a, v] with
  #                        r: blend radius for linear move in m
  #                        a: accleration for linear move in m/s^2
  #                        v: velocity for linear move in m/s
  # param max_forces: maximum allowed absolute force in N along the reference pose's x, y, and z axis as vector [Fx, Fy, Fz]
  # param ignore_dists: array of [start_dist, end_dist] ignore the force value within these distances from the
  #                     start and end point, respectively
  #                     (gets around high force readings from acceleration / deceleration)
  # param refrence_pose: measure the allowed forces along the axes of this pose, defaults to the robot's base,
  #                      x, y, and z values of the pose are ignored
  # return: True if end of linear move was reached, else False
  def movel_checkforce(p_target, move_parameters, max_forces, ignore_dists=[0.0, 0.0], reference_pose=p[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]):

    global p_thread_move_target = p_target
    global thread_move_params = move_parameters
    global thread_target_reached = False
    local p_current = get_actual_tcp_pose()  # current pose
    local p_start = get_actual_tcp_pose()  # start pose of move

    # we use this thread to do the moving
    thread move_thread():
      movel(p_thread_move_target, a=thread_move_params[0], v=thread_move_params[1], r=thread_move_params[2])
      thread_target_reached = True
      sync()
      sync()
    end

    # spin the moving thread and keep track of the force
    move_thread_handler = run move_thread()
    while(not thread_target_reached):
      p_current = get_actual_tcp_pose()
      global current_force_vector = get_tcp_force_in_frame(reference_pose)
      if point_dist(p_current, p_start) > ignore_dists[0] and point_dist(p_current, p_target) > ignore_dists[1]:
        if (norm(current_force_vector[0]) > max_forces[0]) or (norm(current_force_vector[1]) > max_forces[1]) or (norm(current_force_vector[2]) > max_forces[2]):
          kill move_thread_handler
          stopl(1)  # TODO: make this value accessible?
          return False
        end
      end
      sync()
    end
    return True
  end


  # Note 1 to self: a target pose in a feature can be converted to the robot's base frame by
  # using pose_in_base = pose_trans(feature_name, pose_in_feature)
  ############################################################################
  # Copyright (C) Danish Technological Institute - All Rights Reserved       #
  # Unauthorized copying of this file, via any medium is strictly prohibited #
  # Proprietary and confidential                                             #
  # Written by AUTHOR <AUTH@dti.dk>, MONTH YEAR                              #
  #                                                                          #
  # Calculation of poses by offsetting a given pose                          #
  #                                                                          #
  # Version                                                                  #
  dti_relative_poses_version = 1                                             #
  #                                                                          #
  ############################################################################

  def get_dti_relative_poses_version():
    return dti_relative_poses_version
  end

  def get_dti_relative_poses_deps():
    # NO DEPS
    return True
  end

  # TODO: testing
  # Note: Poses in UR-script are given as [translation, axis-angle-rotation],
  # NOT [translation, rpy]!!!


  # calculate a pose by giving an offset to a "base"-pose
  # param base_pose: pose that will be offset
  # param pose_delta: amount to offset along each axis of base_pose
  def p_rel(base_pose, pose_delta=p[0, 0, 0, 0, 0, 0]):
    return pose_trans(base_pose, pose_delta)
  end


  # calculate a pose by giving an offset to a "base"-pose in one dimension
  # param base_pose: pose that will be offset
  # param delta: offset along axis in meters / radians
  # param axis: number of axis along which to offset, x=0, y=1, ..., must be in [0, 5]
  def p_rel_1D(base_pose, delta, axis):
    local p_delta = p[0, 0, 0, 0, 0, 0]
    p_delta[axis] = delta
    return p_rel(base_pose, p_delta)
  end


  # offset a pose along its x-axis, see documentation of p_rel_1D
  def p_rel_x(base_pose, delta):
    return p_rel_1D(base_pose, delta, 0)
  end


  # offset a pose along its y-axis, see documentation of p_rel_1D
  def p_rel_y(base_pose, delta):
    return p_rel_1D(base_pose, delta, 1)
  end


  # offset a pose along its z-axis, see documentation of p_rel_1D
  def p_rel_z(base_pose, delta):
    return p_rel_1D(base_pose, delta, 2)
  end


  # offset a pose by rotating around its x-axis in rad, see documentation of p_rel_1D
  def p_rel_Rx(base_pose, delta):
    return p_rel_1D(base_pose, delta, 3)
  end


  # offset a pose by rotating around its y-axis in rad, see documentation of p_rel_1D
  def p_rel_Ry(base_pose, delta):
    return p_rel_1D(base_pose, delta, 4)
  end


  # offset a pose by rotating around its z-axis in rad, see documentation of p_rel_1D
  def p_rel_Rz(base_pose, delta):
    return p_rel_1D(base_pose, delta, 5)
  end
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: EGH-SCHUNK, 1.0.1, SCHUNK GmbH & Co. KG
  #   Type: SCHUNK EGH Gripper
    EGH = rpc_factory("xmlrpc", "http://127.0.0.1:40408/RPC2")
  global error_updated = False
  global error_internal = 0
  def EGH_error():
          if EGH.getActStatus() != 3:
              if error_updated == False:
                  error_internal = EGH.getDetailDeviceStatus(1)
                  error_updated = True
              end
              return error_internal
          else:
              error_updated = False
              error_internal = 0
              return 0
          end
  end
  def EGH_reference_ok():
          sync()
          return EGH.get_Referenced()
  end
  def EGH_is_success():
          sync()
          return EGH.isSuccess()
  end
  def EGH_is_blocked():
          sync()
          return EGH.isBlocked()
  end
  def EGH_is_endstop():
          sync()
          return EGH.isEndStop()
  end
  def EGH_is_closed():
          sync()
          return EGH.isClosed()
  end
  def EGH_is_open():
          sync()
          return EGH.isOpen()
  end
  def EGH_in_pos():
          sync()
          return EGH.isInPosition()
  end
  def EGH_actual_pos():
          sync()
          return EGH.get_CurrentPosition()
  end
  def EGH_status():
          sync()
          return EGH.getActStatus()
  end
  def EGH_error_check(name):
      local err =  EGH_status()
      if (err != 3):
          local err =  EGH_error()
          err_msg = EGH.getErrorMsg(err)
          textmsg(name, err_msg)
          popup(err_msg, title=name, error=True, blocking=True)
      end
      EGH_conn_check(name)
  end
  def EGH_conn_check(name):
      if (not EGH.is_connected()):
          err_msg = "Gripper disconnected"
          textmsg(name, err_msg)
          popup(err_msg, title=name, error=True, blocking=True)
          halt
      end
  end
  def EGH_goto_pos(value):
          sync()
      EGH.cmdPositioning(value)
  end
  def EGH_gripped_workpiece(wp):
      return EGH.isGrippedWp(wp)
  end

  EGH.resetPrgBreak()
  Gripper_LB_Enabled = True
  if (Gripper_LB_Enabled):
    set_digital_out(0, False)
    set_digital_out(1, True)
  end
  # end: URCap Installation Node
  # begin: URCap Installation Node
  #   Source: SCHUNK Gripper EGI for UR, 0.1.1, SCHUNK GmbH & Co.
  #   Type: SCHUNK EGI Gripper
  ##################################
  ### SCHUNK EGI VARS            ###
  ##################################


  # Connection data:
  SCHUNK_EGI_HOST = "127.0.0.1"
  SCHUNK_EGI_PORT = "56789"
  global SCHUNK_egi_daemon = rpc_factory("xmlrpc", "http://"+ SCHUNK_EGI_HOST + ":" + SCHUNK_EGI_PORT )

  egiTargetPos = 0
  egiPosTolerance = 0.5

  ##################################
  ### SCHUNK egi HELPER FUNC     ###
  ##################################


  def egiPopup(text):
  	popup(text + str_cat(" Errorcode(int): ", SCHUNK_egi_daemon.egi_error_code()) , "SCHUNK EGI ERROR", warning=False, error=True, blocking=True)
  end

  def setTargets(TargetPos, PosTol):
  	egiTargetPos = TargetPos
  	egiPosTolerance = PosTol
  end


  def egiIsInPos():
  	return egiTargetPosReached()
  end


  def egiGraspOK():
  	local posOk = norm( (egiActualPosition()/1000.0) - egiTargetPos ) < egiPosTolerance
  	local gripped = SCHUNK_egi_daemon.egi_gripped()

  	if gripped and posOk:
  		return True
  	else:
  		return False
  	end
  end





  ##################################
  ### SCHUNK EGI XML-RPC CONTROL ###
  ##################################

  def egiReferencing(sync = True):
  	local success = SCHUNK_egi_daemon.egi_referencing(sync)

  	if not success:
  		egiPopup("Error in egi_referencing()")
  	end

  	return success
  end


  def egiRestartModule(sync = True):
  	local shutdown_ok = SCHUNK_egi_daemon.egi_prepare_shutdown()
  	sleep(1)
  	local success = False

  	if SCHUNK_egi_daemon.egi_ready_shutdown():
  		success = SCHUNK_egi_daemon.egi_restart_module(sync)
  	else:
  		success = False
  		egiPopup("EGI is not ready for shutdown")
  	end

  	if not success:
  		egiPopup("Error in egi_restart_module()")
  	end

  	return success
  end

  def egiPrepareShutdown():
  	local shutdown_ok = SCHUNK_egi_daemon.egi_prepare_shutdown()
  	sleep(1)
  	local success = True

  	if not SCHUNK_egi_daemon.egi_ready_shutdown():
  		success = False
  		egiPopup("EGI is not ready for shutdown")
  	end

  	return success
  end

  def egiPosMove(position, speed, sync):

  	local success = SCHUNK_egi_daemon.egi_pos_move(position*1000, speed*1000, sync)

  	if not success:
  		egiPopup("Error in egi_pos_move()")
  	end

  	return success
  end


  def egiRelPosMove(position, speed, sync):
  	local success = SCHUNK_egi_daemon.egi_rel_pos_move(position*1000, speed*1000, sync)

  	if not success:
  		egiPopup("Error in egi_rel_pos_move()")
  	end

  	return success
  end

  def egiGripWorkPiece(force, inside, sync):
  	local success = SCHUNK_egi_daemon.egi_grip_work_piece(force*1000, inside, sync)

  	if (not success) and egiFatalError() :
  		egiPopup("Error in egi_grip_work_piece()")
  	end

  	return success
  end

  def egiReleaseWorkPiece(sync):
  	local success = SCHUNK_egi_daemon.egi_release_work_piece(sync)

  	if (not success) and egiFatalError():
  		egiPopup("Error in egi_release_work_piece()")
  	end

  	return success
  end



  def egiStop():
  	local success = SCHUNK_egi_daemon.egi_stop()

  	if not success:
  		egiPopup("Error in egi_stop()")
  	end

  	return success
  end


  def egiFastStop():
  	local success = SCHUNK_egi_daemon.egi_quick_stop()

  	if not success:
  		egiPopup("Error in egi_quick_stop()")
  	end

  	return success
  end


  def egiStatusString():
  	return SCHUNK_egi_daemon.egi_status_string()
  end


  def egiActualPosition():
  	return SCHUNK_egi_daemon.egi_actual_position()
  end

  def egiAckError():
  	local success = SCHUNK_egi_daemon.egi_acknowledge_error()

  	if not success:
  		egiPopup("Error in egi_acknowledge_error()")
  	end

  	return success
  end

  def egiTargetPosReached():
  	return SCHUNK_egi_daemon.egi_target_pos_reached()
  end

  def egiModuleRef():
  	return SCHUNK_egi_daemon.egi_module_ref()
  end

  def egiWarning():
  	return SCHUNK_egi_daemon.egi_warning()
  end


  def egiFatalError():
  	return SCHUNK_egi_daemon.egi_fatal_error()
  end

  def egiGripped():
  	return SCHUNK_egi_daemon.egi_gripped()
  end

  def egiNoPart():
  	return SCHUNK_egi_daemon.egi_no_part_detect()
  end


  def egiConnected():
  	return SCHUNK_egi_daemon.egi_connected()
  end


  def egiErrorCode():
  	return SCHUNK_egi_daemon.egi_error_code()
  end


  ######################################
  ### SCHUNK EGI XML-RPC CONTROL END ###
  ######################################
  # end: URCap Installation Node
  global Waypoint_1_p=p[-.002828225860, -.210201384715, .305113883890, 1.391025263603, 1.178117575654, 1.090990503136]
  global Waypoint_1_q=[1.5663269758224487, -2.207759996453756, 2.139740769063131, -1.446153239612915, -1.6815841833697718, 1.6957852840423584]
  $ 1 "Robot Program"
  $ 2 "MoveJ"
  $ 3 "Waypoint_1" "breakAfter"
  set_tcp(p[0.00148,-0.1103,0.13452,-1.567,0.0,0.0])
  movej(get_inverse_kin(Waypoint_1_p, qnear=Waypoint_1_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 4 "Set"
  set_tcp(p[-0.0567,0.0325,0.0062,-0.0037,-0.0098,-1.5604])
  $ 5 "board_pose≔p_rel(get_actual_tcp_pose(),p[0.0175,-0.2235,0.42188,0,0,0])"
  global board_pose= p_rel ( get_actual_tcp_pose (),p[0.0175,-0.2235,0.42188,0,0,0])
  $ 6 "board_pose≔p_rel(board_pose,p[0,0,0,3.14,0,0])"
  global board_pose= p_rel (board_pose,p[0,0,0,3.14,0,0])
  $ 7 "board_pose[2] = board_pose[2]+0.01"
  board_pose[2] = board_pose[2]+0.01
  $ 10 "Set"
  set_tcp(p[0.00148,-0.1103,0.13452,-1.567,0.0,0.0])
  $ 11 "MoveL"
  $ 12 "board_pose" "breakAfter"
  movel(board_pose, a=1.2, v=0.25)
end
